# Generated by Django 5.1.3 on 2024-11-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('street_num', models.IntegerField()),
                ('street_name', models.TextField()),
                ('apt_num', models.TextField()),
                ('zipcode', models.IntegerField()),
                ('dob', models.TextField()),
                ('dor', models.TextField()),
                ('party', models.TextField()),
                ('prec_num', models.TextField()),
                ('v20s', models.BooleanField()),
                ('v21t', models.BooleanField()),
                ('v21p', models.BooleanField()),
                ('v22g', models.BooleanField()),
                ('v23t', models.BooleanField()),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
