# Generated by Django 5.1.3 on 2024-11-21 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_item_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='customer1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='project.customer'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='customer2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='project.customer'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('image_self', models.ImageField(blank=True, upload_to='')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='project.customer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='project.customer')),
            ],
        ),
    ]
