# Generated by Django 5.1.3 on 2024-12-05 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='project.customerorder'),
            preserve_default=False,
        ),
    ]
