# Generated by Django 5.1.1 on 2024-10-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0002_alter_profile_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_address',
            field=models.TextField(),
        ),
    ]
