# Generated by Django 5.1.2 on 2024-10-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
